cookie:
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$2Lz1ogv9lop8Ci7pmWD7vuhQ9zm8xuITnuwPGDOlS59OZ0ThobBUm
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$Gv5YAbI/x10TzvRJkteGb.Rog1ZEcL9YgxJ1SVAUVwv5Qwx44uJCC
preauthorized:
  emails:
  - melsby@gmail.com
