cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    gladysm:
      email: gladysmawarni@gmail.com
      name: gladys
      password: $2b$12$/gCPx0Xr4xJYpl/DPyupc.NRE57BTqaw7xRVkIKlk.dMy4abLDkjC
preauthorized:
  emails:
  - jose@gmail.com
  - alexandre@gmail.com
